In [1]:
import numpy as np

METHOD 1: Transpose <p>
This following piece of code will create 5 random matrices consisting of 0's and 1's by transposing the position of the 0's once the 1's are placed. This method will continue until all entries are filled. The determinants of these matrices will be shown to see what they are based on this method. The first piece of code will run for 5x5 matrices, and the second piece of code for 20x20 matrices.

In [2]:
# Create 5x5 matrix and apply the transpose formula
def create_matrix():
    matrix = np.zeros((5, 5), dtype=int)
    positions = [(i, j) for i in range(5) for j in range(5)]

    while positions:
        position = positions.pop(np.random.randint(len(positions)))
        matrix[position] = 1
        transpose_position = (position[1], position[0])
        matrix[transpose_position] = 0

    return matrix

# Number of matrices in my output
def main():
    num_matrices = 5

    
# Print out the matrix and the determinant
    for i in range(num_matrices):
        matrix = create_matrix()
        print(f"Matrix {i + 1}:\n{matrix}\n")

        determinant = np.linalg.det(matrix)
        print(f"Determinant of Matrix {i + 1}: {determinant}\n")

if __name__ == "__main__":
    main()


Matrix 1:
[[0 1 1 0 1]
 [0 0 1 0 1]
 [0 0 0 0 1]
 [1 1 1 0 0]
 [0 0 0 1 0]]

Determinant of Matrix 1: 1.0

Matrix 2:
[[0 0 0 1 0]
 [1 0 1 1 1]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [1 0 1 1 0]]

Determinant of Matrix 2: 0.0

Matrix 3:
[[0 1 1 1 1]
 [0 0 1 0 0]
 [0 0 0 1 1]
 [0 1 0 0 1]
 [0 1 0 0 0]]

Determinant of Matrix 3: 0.0

Matrix 4:
[[0 1 1 0 0]
 [0 0 0 1 0]
 [0 1 0 0 1]
 [1 0 1 0 1]
 [1 1 0 0 0]]

Determinant of Matrix 4: 3.0000000000000004

Matrix 5:
[[0 1 0 1 1]
 [0 0 1 1 0]
 [1 0 0 0 1]
 [0 0 1 0 1]
 [0 1 0 0 0]]

Determinant of Matrix 5: 2.0



In [7]:
# Create 20x20 matrix and apply transpose formula
def create_matrix():
    matrix = np.zeros((20, 20), dtype=int)
    positions = [(i, j) for i in range(20) for j in range(20)]

    while positions:
        position = positions.pop(np.random.randint(len(positions)))
        matrix[position] = 1
        transpose_position = (position[1], position[0])
        matrix[transpose_position] = 0

    return matrix

# Number of matrices in my output
def main():
    num_matrices = 5

# Print out the matrix and the determinant
    for i in range(num_matrices):
        matrix = create_matrix()
        print(f"Matrix {i + 1}:\n{matrix}\n")

        determinant = np.linalg.det(matrix)
        print(f"Determinant of Matrix {i + 1}: {determinant}\n")

if __name__ == "__main__":
    main()


Matrix 1:
[[0 0 1 0 0 1 0 0 1 0 1 1 1 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 1 1 1 0 1 1 0 0 1 0 0 1 0 1]
 [0 1 0 1 0 0 1 1 0 1 0 0 1 0 0 1 1 0 1 1]
 [1 1 0 0 1 0 0 1 1 1 1 0 0 1 0 1 0 0 0 1]
 [1 1 1 0 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1]
 [0 1 1 1 0 0 0 1 0 0 1 0 1 0 1 0 1 1 1 0]
 [1 0 0 1 0 1 0 0 0 0 1 1 1 0 0 0 0 1 1 0]
 [1 0 0 0 1 0 1 0 1 1 1 0 1 0 0 0 1 1 0 1]
 [0 0 1 0 1 1 1 0 0 1 1 0 1 1 1 0 1 0 0 0]
 [1 1 0 0 0 1 1 0 0 0 1 0 1 1 1 0 0 1 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 1]
 [0 0 1 1 0 1 0 1 1 1 0 0 0 0 1 0 0 1 0 1]
 [0 1 0 1 0 0 0 0 0 0 1 1 0 1 0 0 0 1 0 0]
 [1 1 1 0 0 1 1 1 0 0 1 1 0 0 0 0 1 0 1 1]
 [1 0 1 1 0 0 1 1 0 0 1 0 1 1 0 1 0 1 1 1]
 [1 1 0 0 1 1 1 1 1 1 0 1 1 1 0 0 0 1 0 1]
 [0 1 0 1 0 0 1 0 0 1 1 1 1 0 1 1 0 1 1 0]
 [1 0 1 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0]
 [1 1 0 1 0 0 0 1 1 1 1 1 1 0 0 1 0 0 0 0]
 [1 0 0 0 0 1 1 0 1 1 0 0 1 0 0 0 1 1 1 0]]

Determinant of Matrix 1: -78434.00000000003

Matrix 2:
[[0 0 1 0 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 0]
 [1 0 1 1 1 0 1 0 1 0 0 0 1 0 

METHOD 2: Reflection <p>
This following piece of code will create 5 random matrices consisting of 0's and 1's by reflection horizontally the position of the 0's once the 1's are placed. This method will continue until all entries are filled. The determinants of these matrices will be shown to see what they are based on this method. The first piece of code will run for 5x5 matrices, and the second piece of code for 20x20 matrices.

In [11]:
# Create 5x5 matrix and apply reflection formula
def create_matrix():
    matrix = np.zeros((5, 5), dtype=int)
    positions = [(i, j) for i in range(5) for j in range(5)]
    
    while positions:
        position = positions.pop(np.random.randint(len(positions)))
        matrix[position] = 1
        reflection_position = (position[0], 4 - position[1])
        matrix[reflection_position] = 0
    
    return matrix

# Number of matrices in my output
def main():
    num_matrices = 5

# Print out the matrix and the determinant
    for i in range(num_matrices):
        matrix = create_matrix()
        print(f"Matrix {i + 1}:\n{matrix}\n")
        
        determinant = np.linalg.det(matrix)
        print(f"Determinant of Matrix {i + 1}: {determinant}\n")

if __name__ == "__main__":
    main()


Matrix 1:
[[1 1 0 0 0]
 [1 1 0 0 0]
 [0 1 0 0 1]
 [1 0 0 1 0]
 [0 0 0 1 1]]

Determinant of Matrix 1: 0.0

Matrix 2:
[[1 0 0 1 0]
 [1 0 0 1 0]
 [1 1 0 0 0]
 [1 0 0 1 0]
 [1 1 0 0 0]]

Determinant of Matrix 2: 0.0

Matrix 3:
[[0 0 0 1 1]
 [0 1 0 0 1]
 [1 1 0 0 0]
 [1 0 0 1 0]
 [0 1 0 0 1]]

Determinant of Matrix 3: 0.0

Matrix 4:
[[1 1 0 0 0]
 [0 1 0 0 1]
 [0 0 0 1 1]
 [1 0 0 1 0]
 [0 0 0 1 1]]

Determinant of Matrix 4: 0.0

Matrix 5:
[[0 1 0 0 1]
 [1 0 0 1 0]
 [0 0 0 1 1]
 [0 1 0 0 1]
 [1 1 0 0 0]]

Determinant of Matrix 5: 0.0



In [10]:
# Create 20x20 matrix and apply reflection formula
def create_matrix():
    matrix = np.zeros((20, 20), dtype=int)
    positions = [(i, j) for i in range(20) for j in range(20)]
    
    while positions:
        position = positions.pop(np.random.randint(len(positions)))
        matrix[position] = 1
        reflection_position = (position[0], 19 - position[1])
        matrix[reflection_position] = 0
    
    return matrix

# Number of matrices in my output
def main():
    num_matrices = 5

# Print out the matrix and the determinant
    for i in range(num_matrices):
        matrix = create_matrix()
        print(f"Matrix {i + 1}:\n{matrix}\n")
        
        determinant = np.linalg.det(matrix)
        print(f"Determinant of Matrix {i + 1}: {determinant}\n")

if __name__ == "__main__":
    main()


Matrix 1:
[[1 1 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 0 0]
 [1 1 1 1 1 0 1 0 0 1 0 1 1 0 1 0 0 0 0 0]
 [1 1 1 0 0 1 1 1 0 0 1 1 0 0 0 1 1 0 0 0]
 [0 0 1 0 0 0 1 1 1 1 0 0 0 0 1 1 1 0 1 1]
 [1 1 0 0 1 0 1 1 0 1 0 1 0 0 1 0 1 1 0 0]
 [0 0 0 0 1 1 0 1 0 0 1 1 0 1 0 0 1 1 1 1]
 [1 1 0 0 0 0 1 0 0 0 1 1 1 0 1 1 1 1 0 0]
 [1 0 0 1 0 1 1 1 0 1 0 1 0 0 0 1 0 1 1 0]
 [0 1 0 0 0 1 1 0 1 1 0 0 1 0 0 1 1 1 0 1]
 [1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 0 0 0]
 [0 1 0 0 0 0 0 1 0 1 0 1 0 1 1 1 1 1 0 1]
 [1 0 1 1 1 1 0 1 1 0 1 0 0 1 0 0 0 0 1 0]
 [1 1 0 0 1 1 0 1 0 1 0 1 0 1 0 0 1 1 0 0]
 [1 0 0 1 1 0 0 1 0 0 1 1 0 1 1 0 0 1 1 0]
 [0 0 0 1 1 1 0 1 1 1 0 0 0 1 0 0 0 1 1 1]
 [1 0 1 1 1 1 1 1 0 1 0 1 0 0 0 0 0 0 1 0]
 [1 1 1 1 0 1 0 1 1 1 0 0 0 1 0 1 0 0 0 0]
 [0 1 1 1 0 1 0 1 1 0 1 0 0 1 0 1 0 0 0 1]
 [0 1 1 1 0 0 1 1 1 1 0 0 0 0 1 1 0 0 0 1]
 [0 1 0 0 0 1 1 1 0 0 1 1 0 0 0 1 1 1 0 1]]

Determinant of Matrix 1: 0.0

Matrix 2:
[[1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 1 1 1 0 0]
 [1 0 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 1 0]
 [